const values = [
  {
    lat: 38.98695,
    lng: -94.61968,
    city: "Overland Park",
    prov: "Kansas",
    state: "United States",
    name: "Meadow Lake Country Club",
  },
  {
    lat: -43.89834,
    lng: 171.70011,
    city: "Ashburton",
    prov: "Canterbury",
    state: "New Zealand",
    name: "Leafield",
  },
  {
    lat: 64.87137,
    lng: 26.72718,
    city: "Juntunen",
    prov: "Northern Ostrobothnia",
    state: "Finland",
    name: "Musta",
  },
  {
    lat: 46.98999,
    lng: -107.83178,
    city: "Mosby",
    prov: "Montana",
    state: "United States",
    name: "North Fork Sage Hen Creek",
  },
  {
    lat: 42.21667,
    lng: 102.06667,
    city: "Elst Hötöliyn Ovoo",
    prov: "Ömnögovĭ",
    state: "Mongolia",
    name: "",
  },
  {
    lat: -22.95,
    lng: 115.883333,
    city: "Mount Florry",
    prov: "",
    state: "Australia",
    name: "",
  },
  {
    lat: 34.2,
    lng: 37.36667,
    city: "Jabal Ru’ūs",
    prov: "Homs",
    state: "Syria",
    name: "ناحية القريتين (Al-Qaryatayn Subdistrict)",
  },
  {
    lat: 31.48038,
    lng: -112.84932,
    city: "Jabal Ru’ūs",
    prov: "Sonora",
    state: "Mexico",
    name: "Cerro El Tullido",
  },
  {
    lat: 12.72261,
    lng: 106.00555,
    city: "Char Tnaol",
    prov: "Kratie",
    state: "Cambodia",
    name: "Char Tnaol",
  },
  {
    lat: 16.72226,
    lng: 76.11456,
    city: "Bhairvadgi",
    prov: "Karnataka",
    state: "India",
    name: "Bhairvadgi",
  },
  {
    lat: -32.88786,
    lng: 134.06667,
    city: "Westall",
    prov: "South Australia",
    state: "Australia",
    name: "Point Westall",
  },
  {
    lat: -1.90898,
    lng: -60.06045,
    city: "Sítio Selva de Pedra",
    prov: "Amazonas",
    state: "Brazil",
    name: "Fazenda Círculo Gaúcho",
  },

  {
    lat: -16.65,
    lng: -58.483333,
    city: "El Vi",
    prov: "Santa Cruz",
    state: "Bolivia",
    name: "Córrego Morro Branco",
  },
  {
    lat: 52.75,
    lng: 101.33333,
    city: "Dayalyk",
    prov: "Buryatiya Republic",
    state: "Russia",
    name: "",
  },
  {
    lat: -12.33333,
    lng: -38.55,
    city: "Sangradouro",
    prov: "Bahia",
    state: "Brazil",
    name: "Sangradouro",
  },
  {
    lat: 55.14191,
    lng: -110.74348,
    city: "Lakeland County",
    prov: "Alberta",
    state: "Canada",
    name: "",
  },
  {
    lat: 66.51091,
    lng: 4.714,
    city: "Akaitcho Lake",
    prov: "Nunavut",
    state: "Canada",
    name: "",
  },
  {
    lat: 34.80387,
    lng: -118.12702,
    city: "Rosamond",
    prov: "California",
    state: "United States",
    name: "Rainbow Farms (historical)",
  },
  {
    lat: 17.9521,
    lng: 37.598,
    city: "Jibāl Wershiqanī",
    prov: "Red Sea",
    state: "Sudan",
    name: "",
  },
  {
    lat: 5.16667,
    lng: 37.9,
    city: "Luk’aluk’ē Bota",
    prov: "Oromiya",
    state: "Ethiopia",
    name: "",
  },
  {
    lat: 12.68,
    lng: 54.12197,
    city: "",
    prov: "Soqatra",
    state: "Yemen",
    name: "",
  },
  {
    lat: 42.18333,
    lng: 53.66667,
    city: "Chagali",
    prov: "",
    state: "Turkmenistan",
    name: "Chagali",
  },
];

export default todayCoords = () => {
  const start = new Date("2022 10 3");
  const now = Date.now();
  const nDays = Math.floor((now - start) / (60 * 60 * 1000 * 24));
  return values[values.length % nDays];
};

// {
//     lat: ,
//     lng: ,
//     city: "",
//     prov: "",
//     state: "",
//     name: "",
//   },
